### ISSUE TITLE
安装没成功。。。

### ISSUE THREAD

**Issue by Finalhell15** [Lycoiref/zhenxun_plugin_intercept_withdraw#1]
文件中没找到intercept_withdraw文件夹
之后的步骤做了
提示构造插件数据失败 intercept_withdraw - <class 'pydantic.error_wrappers.ValidationError'>：1 validation error for PluginData

**Comment by Lycoiref** [comment]
git clone之后会自动生成intercept_withdraw文件夹，如果不是使用git clone下载的，自己新建一个intercept_withdraw文件夹并将__init__.py文件放入即可。

**Comment by Lycoiref** [comment]
> 文件中没找到intercept_withdraw文件夹 之后的步骤做了 提示构造插件数据失败 intercept_withdraw - <class 'pydantic.error_wrappers.ValidationError'>：1 validation error for PluginData

之前readme没更新，现在放到extensive_plugins文件夹下即可

**Comment by Finalhell15** [comment]
依旧报错
[ERROR] init_plugin_config | 构造插件数据失败 intercept_withdraw - <class 'pydantic.error_wrappers.ValidationError'>：1 validation error for PluginData
task
  value is not a valid dict (type=type_error.dict)

**Comment by Lycoiref** [comment]
> 依旧报错 [ERROR] init_plugin_config | 构造插件数据失败 intercept_withdraw - <class 'pydantic.error_wrappers.ValidationError'>：1 validation error for PluginData task value is not a valid dict (type=type_error.dict)

真寻版本？有时间我看一下能否复现错误。

**Comment by Finalhell15** [comment]
真寻V0.1.6.6

**Comment by Lycoiref** [comment]
已修复
