### ISSUE TITLE
真寻1.6.7更新后防撤回报错

### ISSUE THREAD

**Issue by ClaraOWS** [Lycoiref/zhenxun_plugin_intercept_withdraw#2]
更新后报错如下，撤回无反应，请问如何解决
[ERROR] services | 构造插件数据失败 zhenxun_plugin_intercept_withdraw-main || 错误 <class 'pydantic.error_wrappers.ValidationError'>: 1 validation error for PluginData
task
  value is not a valid dict (type=type_error.dict)

**Comment by Lycoiref** [comment]
> 更新后报错如下，撤回无反应，请问如何解决 [ERROR] services | 构造插件数据失败 zhenxun_plugin_intercept_withdraw-main || 错误 <class 'pydantic.error_wrappers.ValidationError'>: 1 validation error for PluginData task value is not a valid dict (type=type_error.dict)

感谢反馈，预计周末尝试复现解决。:kissing_heart:

**Comment by Lycoiref** [comment]
已修复
